
package com.m2i.tp.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Convertisseur", targetNamespace = "http://service.tp.m2i.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Convertisseur {


    /**
     * 
     * @param montantEuro
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "euroToFranc", targetNamespace = "http://service.tp.m2i.com/", className = "com.m2i.tp.service.EuroToFranc")
    @ResponseWrapper(localName = "euroToFrancResponse", targetNamespace = "http://service.tp.m2i.com/", className = "com.m2i.tp.service.EuroToFrancResponse")
    @Action(input = "http://service.tp.m2i.com/Convertisseur/euroToFrancRequest", output = "http://service.tp.m2i.com/Convertisseur/euroToFrancResponse")
    public double euroToFranc(
        @WebParam(name = "montantEuro", targetNamespace = "")
        double montantEuro);

    /**
     * 
     * @param montantFranc
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "francToEuro", targetNamespace = "http://service.tp.m2i.com/", className = "com.m2i.tp.service.FrancToEuro")
    @ResponseWrapper(localName = "francToEuroResponse", targetNamespace = "http://service.tp.m2i.com/", className = "com.m2i.tp.service.FrancToEuroResponse")
    @Action(input = "http://service.tp.m2i.com/Convertisseur/francToEuroRequest", output = "http://service.tp.m2i.com/Convertisseur/francToEuroResponse")
    public double francToEuro(
        @WebParam(name = "montantFranc", targetNamespace = "")
        double montantFranc);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuteur", targetNamespace = "http://service.tp.m2i.com/", className = "com.m2i.tp.service.GetAuteur")
    @ResponseWrapper(localName = "getAuteurResponse", targetNamespace = "http://service.tp.m2i.com/", className = "com.m2i.tp.service.GetAuteurResponse")
    @Action(input = "http://service.tp.m2i.com/Convertisseur/getAuteurRequest", output = "http://service.tp.m2i.com/Convertisseur/getAuteurResponse")
    public String getAuteur();

}
