
package com.m2i.tp.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConvertisseurImplService", targetNamespace = "http://service.tp.m2i.com/", wsdlLocation = "http://formation17:8080/serveurSoap/convertisseur?wsdl")
public class ConvertisseurImplService
    extends Service
{

    private final static URL CONVERTISSEURIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONVERTISSEURIMPLSERVICE_EXCEPTION;
    private final static QName CONVERTISSEURIMPLSERVICE_QNAME = new QName("http://service.tp.m2i.com/", "ConvertisseurImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://formation17:8080/serveurSoap/convertisseur?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTISSEURIMPLSERVICE_WSDL_LOCATION = url;
        CONVERTISSEURIMPLSERVICE_EXCEPTION = e;
    }

    public ConvertisseurImplService() {
        super(__getWsdlLocation(), CONVERTISSEURIMPLSERVICE_QNAME);
    }

    public ConvertisseurImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTISSEURIMPLSERVICE_QNAME, features);
    }

    public ConvertisseurImplService(URL wsdlLocation) {
        super(wsdlLocation, CONVERTISSEURIMPLSERVICE_QNAME);
    }

    public ConvertisseurImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTISSEURIMPLSERVICE_QNAME, features);
    }

    public ConvertisseurImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertisseurImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Convertisseur
     */
    @WebEndpoint(name = "ConvertisseurImplPort")
    public Convertisseur getConvertisseurImplPort() {
        return super.getPort(new QName("http://service.tp.m2i.com/", "ConvertisseurImplPort"), Convertisseur.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Convertisseur
     */
    @WebEndpoint(name = "ConvertisseurImplPort")
    public Convertisseur getConvertisseurImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.tp.m2i.com/", "ConvertisseurImplPort"), Convertisseur.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTISSEURIMPLSERVICE_EXCEPTION!= null) {
            throw CONVERTISSEURIMPLSERVICE_EXCEPTION;
        }
        return CONVERTISSEURIMPLSERVICE_WSDL_LOCATION;
    }

}
